name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ayushjain094
          password: dckr_pat_Wej_fnn7IJzuKRCnFEuE9dSit-Q

      - name: Build Docker image
        run: |
          docker build -t ayushjain094/testable:test .

      - name: Push Docker image to Docker Hub
        run: |
          docker push ayushjain094/testable:test
